server.port: 7003
server.error.include-message: always
spring:
  graphql:
    schema:
      locations: classpath*:graphql/**/
    graphiql:
      path: /graphiql
      enabled: true

# Strongly recommend to set this property to "none" in a production environment!
spring.data.mongodb:
  host: localhost
  port: 27017
  database: review-db


logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.graphql: TRACE

---
spring.config.activate.on-profile: docker
spring:
  graphql:
    schema:
      locations: classpath*:graphql/**/
    graphiql:
      path: /graphiql
      enabled: true
server.port: 7003

spring.data.mongodb.host: mongodb