server.port: 7001
server.error.include-message: always
spring:
  graphql:
    schema:
      locations: classpath*:graphql/**/
    graphiql:
      path: /graphiql
      enabled: true

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.graphql: TRACE

app:
  review-service:
    host: localhost
    port: 7003

---
spring.config.activate.on-profile: docker
spring:
  graphql:
    schema:
      locations: classpath*:graphql/**/
    graphiql:
      path: /graphiql
      enabled: true
server.port: 7001

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.graphql: TRACE

spring.data.mongodb.host: mongodb

app:
  review-service:
    host: review
    port: 7003