springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: com.antonio.microservices.composite.product
  pathsToMatch: /**

server.port: 6999
server.error.include-message: always
spring:
  graphql:
    schema:
      locations: classpath*:graphql/product-composite-service/**/
    graphiql:
      path: /graphiql
      enabled: true
app:
  product-service:
    host: localhost
    port: 7001
  recommendation-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.security: TRACE
    org.springframework.graphql: TRACE

---
spring.config.activate.on-profile: docker

server.port: 6999
spring:
  security:
    user:
      name: user
      password: password
  graphql:
    schema:
      locations: classpath*:graphql/product-composite-service/**/
    graphiql:
      path: /graphiql
      enabled: true
app:
  product-service:
    host: product
    port: 7001
  recommendation-service:
    host: recommendation
    port: 7002
  review-service:
    host: review
    port: 7003